### ISSUE TITLE
What about applying physic gravity ?

### ISSUE THREAD

**Issue by ryancheung** [jwatte/EPIC#1]
@jwatte When considering physic gravity, does this demo also work as intended? If not, could you help me how to do position extrapolation when applying physic gravity? 

I'm kinda new to 3D game development.

**Comment by jwatte** [comment]
This interpolation will generate reasonable (piecewise linear) arcs based on the update rate received. If you receive, say, 10 or 20 updates per second, it will look fine.
If you want to display an entity by using client-side co-simulation, then position extrapolation/interpolation isn't really the right tool, though. There are other approaches you have to take in that case.
